### PR TITLE
trustnobank.eth to domains.json

### PR DESCRIPTION
**Pull request by dex4k**
As before a tentative PR. As soon as you confirm you are happy to list the domain on ENSnow I will transfer ownership to the smart contract.

### CODE REVIEW

**Comment by Arachnid** [comment]
LGTM.

**Comment by dex4k** [comment]
Transferred to the smart contract ready to go!

**Comment by dex4k** [comment]
@Arachnid for some reason this domain still isn't showing on ENSnow, any reason that might be? The settings I entered into the smart contract were the same as the other domains so they should be fine.

The only thing I can think of is it did have a few subdomains already created before transfer to the smart contract. I just added resolvers and addresses to them in case that was the issue but that made no difference.

If those domains are causing a conflict is there any way to fix the issue?

If it can't be fixed I just registered trustsnobank.eth which I can replace this with instead.

**Comment by dex4k** [comment]
I'm going to make an educated guess that the subdomains have caused a conflict with the smart contract since the contract has no record of them. And if so this issue can't really be fixed because the whole point of the smart contract is subdomains cannot be removed.

So I will resign myself to the fact my own idiocy cost me a fiver and transfer ownership of trustsnobank.eth to the smart contract and submit a new PR removing this domain and adding that one in its place to resolve the issue.

**Comment by Arachnid** [comment]
There's no 'conflict' here - the contract and the dapp neither no nor care what subdomains existed before you transferred the domain in.

It appears the name wasn't caught by the last deploy. I'll redeploy now.

**Comment by dex4k** [comment]
Much simpler than I expected then, thank you. In that case please delete the new PR for the other domain. Cheers!

**Pull request merged**
