### PR TITLE
Added "blockchaincontracts" name

### PR DESCRIPTION
**Pull request by aetgit**
Hopefully I did this right. Literally my first time ever doing anything on Github.

### CODE REVIEW

**Comment by dex4k** [comment]
You forgot the comma and the end of your line! You have to add that or the file won't work.

**Comment by aetgit** [comment]
Whew! Sorry about that! Thanks for double checking. I'll be as careful as
possible! I'm just learning. Exciting stuff though.

**Comment by dex4k** [comment]
No problem, I'm very much in the learning phase myself!

To fix this just go to "files changed" then when it shows the file, there should be three dots in the top right of the box showing the list of domains, click that then "edit", then you can add the comma and hit save.

The maintainers can also fix it themselves before they merge the change, so the website itself wouldn't have been broken, but it's good practice to submit changes that don't need altering and now you know for the future :)

**Comment by aetgit** [comment]
Thank you for holding my hand. Haha. Should be fixed.

**Pull request merged**
