### PR TITLE
added two new domains

### PR DESCRIPTION
**Pull request by dex4k**
just added two new registered domains to json :)

### CODE REVIEW

**Comment by Arachnid** [comment]
Sorry, but I think the demand for these amongst subdomain registrants is going to be very limited. I can't justify adding them to every search result.

**Comment by dex4k** [comment]
Okay, that's understandable. Could the contract send my domains back to me as they aren't listed?

**Comment by Arachnid** [comment]
No; like it says in the migration guide, by transferring the domains there they're permanently assigned to the subdomain registrar. You can delist/relist them, change the price, change who gets the fees and has control etc, but you can't get ownership of the domains back.

**Comment by dex4k** [comment]
Okay. But if they're not listed, can any subdomains still actually be registered? Could other frontends aside from ENSnow make them accessible to their users? What's the situation? I was under the impression it has to be on ENSnow to be pulled to other frontends, if this is incorrect and other frontends can still show the domain for listing, that's cool.

**Comment by dex4k** [comment]
Re-reading the docs, it seems I was mistaken and the smart contract is separate from whitelisting on ENSnow, so other frontends can still list those domains. If that's correct it's no worries!

**Comment by Arachnid** [comment]
That's right.

**Comment by dex4k** [comment]
Excellent, that's no trouble then.

**Pull request closed without merging**
