### PR TITLE
resolve npm warnings

### PR DESCRIPTION
**Pull request by celeduc**
Addressed some warnings from Node Package Manager:
* Add license information
* Add repo link
* Remove webpack-dev-server from the production group
* Add a peer dependency

### CODE REVIEW

**Comment by celeduc** [comment]
Build is totally borked and it's not just me. So I'm going to fix the build, then re-submit.

**Comment by Arachnid** [comment]
I believe the build is now fixed; do you want to keep this PR open?

**Comment by celeduc** [comment]
Updated to just fix the npm warnings.

**Comment by Arachnid** [comment]
Thanks!

**Pull request merged**
